export const TRANSLATIONS = {
  en: {
    appName: "Tarjim Translate",
    translate: "Translate",
    history: "History",
    favorites: "Favorites",
    textTab: "Text",
    voiceTab: "Voice",
    translateButton: "Translate",
    translating: "Translating...",
    sourcePlaceholder: "Enter text to translate...",
    targetPlaceholder: "Translation...",
    detectedLanguage: "Detected",
    clearText: "Clear text",
    copied: "Copied!",
    offlineMode: "Offline Mode",
    offlineActive: "Offline mode active. Instant cache used.",
    offlineBanner: "You are offline. Instant translation lookup active.",
    transliteration: "Pronunciation Guide",
    explanation: "Nuance & Word Breakdown",
    speechError: "Speech recognition failed or not supported.",
    speakTranslated: "Listen to translation",
    copiedToast: "Copied to clipboard",
    favoriteAdded: "Added to favorites",
    favoriteRemoved: "Removed from favorites",
    welcomeTitle: "English ⟷ Arabic Translation",
    historyTitle: "Translation History",
    noHistory: "No voice or text translations recorded yet.",
    noFavorites: "Your starred/saved translations will show here.",
    clearAll: "Clear All",
    settings: "Settings",
    darkMode: "Dark Theme",
    offlineToggle: "Simulate Offline Mode",
    vibrationFeedback: "Haptic Vibrations",
    appLanguage: "App Interface Language",
    speakTitle: "Voice Translation",
    speakInstruction: "Press mic to speak in source language",
    listening: "Listening dynamically...",
    stopListening: "Stop Recording",
    voiceTranslationPlaceholder: "Spoken translation result.",
    close: "Close",
    genderMale: "Male Voice",
    genderFemale: "Female Voice",
    toggleInterface: "العربية",
    learnMore: "Word dictionary context generated on-the-fly.",
    quickPhrases: "Quick Phrases",
    swapLanguages: "Swap languages",
    apiWarning: "Offline translation is using offline smart matches.",
    tapToTranslate: "Tap to translate this",
    allCleared: "All cleared!",
  },
  ar: {
    appName: "مترجم ترجم",
    translate: "ترجمة",
    history: "السجل",
    favorites: "المفضلة",
    textTab: "نصي",
    voiceTab: "صوتي",
    translateButton: "ترجم الآن",
    translating: "جاري الترجمة...",
    sourcePlaceholder: "أدخل النص للترجمة هنا...",
    targetPlaceholder: "الترجمة...",
    detectedLanguage: "تم اكتشاف",
    clearText: "مسح النص",
    copied: "تم النسخ!",
    offlineMode: "وضع عدم الاتصال",
    offlineActive: "وضع عدم الاتصال نشط. تم استخدام المخزن المؤقت السريع.",
    offlineBanner: "أنت في وضع عدم الاتصال بالشبكة. تفعيل البحث الفوري عن الترجمة.",
    transliteration: "دليل النطق الصوتي",
    explanation: "توضيحات سياقية وبلاغية",
    speechError: "فشلت ميزة التعرف على الصوت أو أنها غير مدعومة.",
    speakTranslated: "الاستماع للترجمة",
    copiedToast: "تم النسخ إلى الحافظة",
    favoriteAdded: "تم الإضافة للمفضلة",
    favoriteRemoved: "تمت الإزالة من المفضلة",
    welcomeTitle: "الترجمة بين العربية والإنجليزية",
    historyTitle: "سجل الترجمات",
    noHistory: "لم يتم تسجيل أي ترجمات نصية أو صوتية بعد.",
    noFavorites: "الترجمات التي قمت بتمييزها بنجمة ستظهر هنا.",
    clearAll: "مسح الكل",
    settings: "الإعدادات",
    darkMode: "المظهر الداكن",
    offlineToggle: "محاكاة وضع أوفلاين",
    vibrationFeedback: "الاهتزاز اللمسي",
    appLanguage: "لغة واجهة التطبيق",
    speakTitle: "الترجمة الصوتية",
    speakInstruction: "اضغط على المايك للتحدث باللغة المصدر",
    listening: "جاري الاستماع الآن...",
    stopListening: "إيقاف التسجيل",
    voiceTranslationPlaceholder: "ستظهر الترجمة الصوتية هنا.",
    close: "إغلاق",
    genderMale: "صوت ذكوري",
    genderFemale: "صوت أنثوي",
    toggleInterface: "English",
    learnMore: "يتم إنشاء سياق القاموس ومرادفات الكلمات تلقائياً.",
    quickPhrases: "مسارات وعبارات سريعة",
    swapLanguages: "تبديل اللغات",
    apiWarning: "تستخدم الترجمة غير المتصلة بالإنترنت مطابقات ذكية مخزنة.",
    tapToTranslate: "النقر لترجمة هذه العبارة",
    allCleared: "تم مسح كل المحتوى!",
  },
};
